# Generated by Django 5.1.4 on 2024-12-28 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('vocational', 'Vocational Studies'), ('all', 'All Streams')], max_length=20)),
                ('description', models.TextField(help_text='Brief description of the job or course.')),
                ('eligibility', models.TextField(help_text='Eligibility criteria for this role.')),
                ('duration', models.CharField(help_text='Duration of the course or preparation time.', max_length=50)),
                ('skills_needed', models.TextField(help_text='Skills needed to excel in this career.')),
                ('career_opportunities', models.TextField(help_text='Potential job roles after pursuing this career.')),
                ('avg_salary', models.CharField(help_text='Average salary range for this career.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRoleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('max_score', models.IntegerField(help_text='Maximum score for this question.')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aiguide.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(10, '10th Grade'), (12, '12th Grade')])),
                ('stream', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('vocational', 'Vocational Studies'), ('undecided', 'Undecided')], default='undecided', max_length=20)),
                ('interests', models.TextField(help_text='Describe hobbies or activities the student enjoys.')),
                ('career_goal', models.CharField(blank=True, help_text='Optional future career goal.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRoleResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score given by the student.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiguide.jobrolequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiguide.studentprofile')),
            ],
        ),
    ]
